### ISSUE TITLE
[invalid]Remove Unnecessary pms.zip File from Repository

### ISSUE THREAD

**Issue by sojijr** [doingdev/pms#1]
### Issue Description:
I have noticed that there is an unnecessary ZIP file (pms.zip) in the repository. I believe this ZIP file is redundant and new contributors or users may mistakenly download and use the ZIP file instead of cloning the repository. This can lead to confusion and difficulties in keeping their code up to date.

### Suggested Action:
I recommend removing the pms.zip file from the repository to keep it clean and avoid any potential confusion. Contributors can always clone the repository using Git to access the latest version.

**Comment by ahmedohakem** [comment]
Thank you @sojijr for the recommendation. I removed the unnecessary ZIP file (pms.zip). Thanks again.
